In [39]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from collections import Counter


In [56]:
X , y = load_iris(return_X_y = True)
np.random.seed(78)
print(X.shape)
print(y.shape)
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.7)

(150, 4)
(150,)


In [31]:
#X_train
#X_test
y_train

array([2, 0, 0, 1, 2, 1, 2, 2, 1, 1, 1, 0, 0, 2, 2, 1, 2, 0, 0, 1, 1, 2,
       0, 1, 0, 2, 1, 1, 1, 0, 2, 0, 2, 1, 0, 2, 0, 0, 1, 2, 2, 0, 1, 2,
       0])

In [32]:
print(X_train.shape[0])
print(y_train.shape)

45
(45,)


In [33]:
def euclidean_distance(x1 , x2) :
  return np.sqrt(np.sum((x1 - x2)**2))

In [34]:
# test function
x1 = np.array([1,2,3])
x2 = np.array([1,2,4])
print(euclidean_distance(x1,x2))


1.0


In [48]:
from sklearn import neighbors
from scipy.spatial import distance
def predict(x , k = 3) :
  distances = []
  for i in range(len(X)):
    distance = euclidean_distance(X_train[i] , x)
    distances.append((distance,y_train[i]))
    #print(distances)

    distances.sort(key = lambda x : x[0])
    neighbors = distances[:k]
    print(f"neighor {neighbors} ")
    labels = [label for _,label in neighbors]
    print(Counter(labels).most_common(1))
    print(f"label {labels}")
    return Counter(labels).most_common(1)[0][0]

In [ ]:
prediction = []
for x in X_test :
  prediction.append(predict(x))
prediction = np.array(prediction)
accuracy = np.mean(prediction == y_test)
print(accuracy)

In [62]:
model = KNeighborsClassifier(n_neighbors = 2, algorithm = 'auto')
model.fit(X_train , y_train)
y_predict = model.predict(X_test)
accuracy = accuracy_score(y_test , y_predict)
print(accuracy)
print(model.algorithm)

0.9428571428571428
auto


In [63]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test , y_predict)
print(cm)

[[35  0  0]
 [ 0 34  1]
 [ 0  5 30]]


In [64]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        35
           1       0.87      0.97      0.92        35
           2       0.97      0.86      0.91        35

    accuracy                           0.94       105
   macro avg       0.95      0.94      0.94       105
weighted avg       0.95      0.94      0.94       105

